exports.todoList = function (slist, d) {
  var pagHTML = `
      <!DOCTYPE html>
      <html>
          <head>
              <meta charset="UTF-8"/>
              <link rel="icon" href="favicon.png"/>
              <link rel="stylesheet" href="w3.css"/>
              <title>Student Management</title>
          </head>
          <body>
          
              <div class="w3-card-4">
  
                  <header class="w3-container w3-teal">
                      <h1>TODO List</h1>
                  </header>
                  <form class="w3-container" method="POST">
                  <fieldset>
                      <legend>Name</legend>
                      
                      <input class="w3-input w3-round" type="text" name="owner">
                  </fieldset>
                  <fieldset>
                      <legend>Description</legend>
                      
                      <input class="w3-input w3-round" type="text" name="description">
                  </fieldset>

                
                  <br/>
                  <button class="w3-btn w3-green w3-mb-2 " type="submit">Add</button>
              </form>
                  <div class="w3-container">
                      <table class="w3-table-all">
                          <tr>
                              <th>Owner</th>
                              <th>Description</th>
                              <th>Date</th>
                              <th>Operations </th>
                              
                          </tr>
                  `;
  for (let i = 0; i < slist.length; i++) {
    pagHTML += `
                  <tr>
                      <td>${slist[i].owner}</td>
                        <td>${slist[i].description}</td>
                        <td>${slist[i].date}</td>
                        <td><a href="/delete/${slist[i].id}">Delete</a>  <a href="/edit/${slist[i].id}">Edit</a></td>
                  </tr>
          `;
  }

  pagHTML += `
              </table>
              </div>
                  <footer class="w3-container w3-blue">
                      <h5>Generated by RPCW2023 in ${d}</h5>
                  </footer>
              </div>
          </body>
      </html>
      `;
  return pagHTML;
};

exports.deleteTodo = function (todo, d) {
  var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Delete Person</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Delete Person</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Name</legend>
                        <label>Owner</label>
                        <input class="w3-input w3-round" type="text" name="owner" readonly value="${todo.owner}">
                        <label>Description</label>
                        <input class="w3-input w3-round" type="text" name="description" readonly value="${todo.owner}">
                    </fieldset>

                   
                    <br/>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by RPCW2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
            `;
  return pagHTML;
};

exports.editTodo = function (todo, d, readOnly = false) {
  var pagHTML = `
      <!DOCTYPE html>
      <html>
          <head>
              <meta charset="UTF-8"/>
              <link rel="icon" href="favicon.png"/>
              <link rel="stylesheet" href="w3.css"/>
              <title>Form demo</title>
          </head>
          <body>
              <div class="w3-card-4">
                  <header class="w3-container w3-purple">
                      <h2>Person Form</h2>
                  </header>
              
                  <form class="w3-container" method="POST">
                      <fieldset>
                          <legend>Name</legend>
                          <label>Owner</label>
                          <input class="w3-input w3-round" type="text" name="owner"`;
  if (readOnly) pagHTML += ` readonly `;

  pagHTML += `value="${todo.owner}">
                          <label>Description</label>
                          <input class="w3-input w3-round" type="text" name="description"`;
  if (readOnly) pagHTML += ` readonly `;

  pagHTML += `value="${todo.description}">
                      </fieldset>
  
                     
                      <br/>`;

  if (!readOnly)
    pagHTML += `<button class="w3-btn w3-purple w3-mb-2" type="submit">Edit</button>`;
  pagHTML += ` </form>
  
                  <footer class="w3-container w3-purple">
                      <h5>Generated by RPCW2023 in ${d} - [<a href="/">Return</a>]</h5>
                  </footer>
              
              </div>
              `;
  return pagHTML;
};
